# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-06 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietheatre', '0002_auto_20200206_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(),
        ),
    ]
